name       : libva-vdpau-driver
version    : 0.7.4
release    : 5
source     :
    - http://www.freedesktop.org/software/vaapi/releases/libva-vdpau-driver/libva-vdpau-driver-0.7.4.tar.bz2 : 155c1982f0ac3f5435ba20b221bcaa11be212c37db548cd1f2a030ffa17e9bb9
license    : GPL-2.0
summary    : libva vdpau driver
component  : xorg.display
description: |
    libva vdpau driver
emul32     : yes
builddeps  :
    - pkgconfig32(libva)
    - pkgconfig32(libva-x11)
    - pkgconfig32(libva-glx)
    - pkgconfig32(vdpau)
    - pkgconfig(vdpau)
    - pkgconfig32(gl)
    - pkgconfig(gl)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %patch -p1 < $pkgfiles/libva-vdpau-driver-0.7.4-glext-missing-definition.patch
    %patch -p1 < $pkgfiles/libva-vdpau-driver-0.7.4-libvdpau-0.8.patch
    %patch -p1 < $pkgfiles/libva-vdpau-driver-0.7.4-VAEncH264VUIBufferType.patch
    %configure
build      : |
    %make
install    : |
    %make_install
