name       : libva-vdpau-driver
version    : 0.7.4
release    : 10
source     :
    - git|https://github.com/xuanruiqi/vdpau-va-driver-vp9.git : 509d3b21a1084b4f492b50cced8835f4cd591c4a
license    : GPL-2.0-or-later
component  : xorg.display
summary    : libva vdpau driver (UNSUPPORTED)
description: |
    libva vdpau driver for Nvidia. Useful for applications that only support vaapi e.g. chromium, shadow, geforce online, etc. (UNSUPPORTED)
emul32     : yes
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libva)
    - pkgconfig32(libva-glx)
    - pkgconfig32(libva-x11)
    - pkgconfig32(vdpau)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
conflicts  :
    - nvidia-vaapi-driver
